image: registry.gitlab.com/pages/hugo:0.89.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  before_script:
  - apk update && apk upgrade && apk add --no-cache git openssh
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
