baseURL = "https://k-mack.gitlab.io/blog/"
defaultContentLanguage = "en"
enableGitInfo = true
footnoteReturnLinkContents = "↩"
theme = "beautifulhugo"
title = "tech dirt nerd"

pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  subtitle = "A Penny for My Thoughts"
  readingTime = true
  commit = "https://gitlab.com/k-mack/blog/-/commit/"

[Author]
  name = "Kevin Macksamie"
#  email = "email@host.com"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "k-mack"
  github = "k-mack"
#  twitter = "username"
#  reddit = "username"
  linkedin = "kmacksamie"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  keybase = "username"

[frontmatter]
  # With `enableGitInfo = true`, configure a post's "last modified" date to be pulled from Git as a last resort;
  # otherwise, Hugo uses Git's history first.
  lastmod = ["lastmod", "date", "publishDate", ":git"]
